# SEO
name: CS Pound Discord Bot
description: The missing link between Discord and Chicken Smoothie.
company: Blustar
twitter:
  username: TailstarTheDog
  card: summary

# Setup
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"

# Plugins
plugins: ['jekyll-paginate', 'jekyll-seo-tag']

#Others
markdown: kramdown
